Cryptography
DarkGV/SEC-Milestone1 pull request #6
Opened 2021-04-12 23:14 UTC by amsce-iscteiul

Encrypting, decrypting, confirming certificate, confirming integrity, diffie-hellman key generation .Still not tested!!!

2021-04-13 01:09 UTC, BodCar requested changes
Missing import statements.

2021-04-13 10:41 UTC, DarkGV requested changes
As @BodCar said, imports are missing. It doesn't make sense to review, today we will have further discussion regarding this PR 🙂

2021-04-13 10:41 UTC, ALonelyDementor commented on milestone1/src/Cryptography/Crypto.java
> +    private static String CIFER_ALGORITHM = "AES/CBC/PKCS5Padding";
CIPHER not CIFER
```suggestion
    private static String CIPHER_ALGORITHM = "AES/CBC/PKCS5Padding";
```

2021-04-15 22:41 UTC, BodCar commented on milestone1/src/Grid.java
> +            grid[prevx][prevy].remove(user);
I don't really understand this. Why are we removing byzantine users from the grid?

2021-04-15 22:41 UTC, BodCar commented on milestone1/src/Grid.java
> +            for (int c = p.y - maxDist; c < collumns; c++) {
Why are we defining posx and posy if we are not using them? We should use them on the for loops.

2021-04-16 08:41 UTC, DarkGV commented
@amsce-iscteiul will you still create the signature class?

2021-04-16 17:51 UTC, merged